const SWIGGY_API_URL =
  "https://www.swiggy.com/dapi/restaurants/list/v5?lat=13.0827&lng=80.2707&page_type=DESKTOP_WEB_LISTING"

const CLOUDINARY_IMAGE_ID_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/"

const RESTAURANT_ID_URL =
  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=13.0827&lng=80.2707&restaurantId=547669&submitAction=ENTER"

const SWIGGY_MENU_API_URL =
  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=13.0827&lng=80.2707&restaurantId=96694&submitAction=ENTER"

// CORS Proxy
export const SWIGGY_API =
  "https://corsproxy.io/?" + encodeURIComponent(SWIGGY_API_URL)

export const CLOUDINARY_IMAGE_ID =
  "https://corsproxy.io/?" + encodeURIComponent(CLOUDINARY_IMAGE_ID_URL)

export const RESTAURANT_ID =
  "https://corsproxy.io/?" + encodeURIComponent(RESTAURANT_ID_URL)

export const SWIGGY_MENU_API =
  "https://corsproxy.io/?" + encodeURIComponent(SWIGGY_MENU_API_URL)

// Static data
export const restaurantList = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "347441",
      name: "The Sandwich World (Original) - Arasaradi",
      uuid: "906a578a-f8b9-4982-83ef-f479bf819f06",
      city: "49",
      area: "SS Colony",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "0a0ca9f553711b94869c64ef4eed1144",
      cuisines: ["Chinese", "Burgers", "Ice Cream"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 27,
      minDeliveryTime: 27,
      maxDeliveryTime: 27,
      slaString: "27 MINS",
      lastMileTravel: 1,
      slugs: {
        restaurant: "the-sandwich-world-ss-colony-ss-colony",
        city: "madurai",
      },
      cityState: "49",
      address: "THENI MAIN ROAD,OPP TO DEVAKI SCAN,KALAVASAL,MADURAI",
      locality: "Theni main road",
      parentId: 213598,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6763379~p=1~eid=00000188-2583-b561-5439-576000710102",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "347441",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.1",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "121109",
      name: "Hotel Pechies",
      uuid: "ac54e469-b48a-47d9-a9a8-bf726261b477",
      city: "49",
      area: "Near Midland Theatre",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "al4jluhwkr1oidajumvn",
      cuisines: ["Biryani", "Grill", "Chinese", "South Indian"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 17,
      minDeliveryTime: 17,
      maxDeliveryTime: 17,
      slaString: "17 MINS",
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant: "hotel-pechies-bethaniyapuram-ss-colony",
        city: "madurai",
      },
      cityState: "49",
      address: "5/2 Opposite Midland Theater, Sampattipuram Main Road, Madurai",
      locality: "Sampattipuram Main Road",
      parentId: 7484,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "0.4 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "121109",
        deliveryTime: 17,
        minDeliveryTime: 17,
        maxDeliveryTime: 17,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.7",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "80290",
      name: "Mukku Kadai K Subbu-sivanandhasalai",
      uuid: "45158d90-e71f-4d60-8383-cde43217c762",
      city: "49",
      area: "Arrapalayam",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "upvwrehlcylgfr082np6",
      cuisines: ["Chinese", "North Indian", "South Indian", "Biryani"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      slaString: "25 MINS",
      lastMileTravel: 2.5999999046325684,
      slugs: {
        restaurant: "mukku-kadai-k-subbu-arrapalayam-ss-colony",
        city: "madurai",
      },
      cityState: "49",
      address:
        "44, SivanthanSalai, Arapalayam Cross Road, Arrapalayam, Madurai",
      locality: "Sivanandhasalai",
      parentId: 6398,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6621456~p=19~eid=00000188-2583-b561-5439-57660071132b",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "2.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "80290",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        lastMileTravel: 2.5999999046325684,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.0",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "80441",
      name: "Zam Zam Shawarma",
      uuid: "cdf40a14-8c7e-4e71-bc24-75fced63a866",
      city: "49",
      area: "Periyar",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "cuo7c4aydl6l8kakdrna",
      cuisines: ["Arabian", "Grill", "Beverages", "Juices"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      slaString: "30 MINS",
      lastMileTravel: 4.099999904632568,
      slugs: {
        restaurant: "zam-zam-shawarma-periyar-periyar",
        city: "madurai",
      },
      cityState: "49",
      address: "141, North Veli Street, Yanaikal Periyar, Madurai",
      locality: "North Veli Street",
      parentId: 18351,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2600, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2600,
        message: "",
        title: "Delivery Charge",
        amount: "2600",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6621465~p=4~eid=00000188-2583-b561-5439-576100710420",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "4 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "80441",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        lastMileTravel: 4.099999904632568,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.8",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "696370",
      name: "Jb Restaurant",
      uuid: "27a84f79-d797-43ea-a134-24dae1d5c1b7",
      city: "49",
      area: "SS Colony",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "f1bc9ddf53de574cdc35ab2f717df234",
      cuisines: ["South Indian", "North Indian", "Chinese", "Biryani"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 15,
      minDeliveryTime: 15,
      maxDeliveryTime: 15,
      slaString: "15 MINS",
      lastMileTravel: 0.5,
      slugs: {
        restaurant: "jb-restaurant-ss-colony-ss-colony",
        city: "madurai",
      },
      cityState: "49",
      address:
        "NO:2, DSP NAGAR, DHINAMALAR AVENUE, BYEPASS ROAD, MADURAI, MADURAI CORPORATION WARD-19, MADURAI, TAMIL NADU-625016",
      locality: "Byepass Road",
      parentId: 110481,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "0.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "696370",
        deliveryTime: 15,
        minDeliveryTime: 15,
        maxDeliveryTime: 15,
        lastMileTravel: 0.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 20,
      new: true,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "128487",
      name: "Pechiamman Veg Restaurant",
      uuid: "0dc281a4-5973-4b73-95b3-53eaf26ec59d",
      city: "49",
      area: "Villapuram",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "alwyynk3gbquidws6h6a",
      cuisines: ["Chinese", "North Indian", "South Indian", "Biryani"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      slaString: "29 MINS",
      lastMileTravel: 6.599999904632568,
      slugs: {
        restaurant: "petchiamman-veg-restaurant-villapuram-periyar",
        city: "madurai",
      },
      cityState: "49",
      address: "no :54-A aruppukottai main road,meenakshi nagar,madurai-625012",
      locality: "Aruppukottai Main Road",
      parentId: 7177,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 4400, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 4400,
        message: "",
        title: "Delivery Charge",
        amount: "4400",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6621821~p=7~eid=00000188-2583-b561-5439-576200710717",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "6.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "128487",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        lastMileTravel: 6.599999904632568,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.2",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "82025",
      name: "Aibaik",
      uuid: "4561a012-2eca-45ab-8508-f61a24c246cf",
      city: "49",
      area: "SS Colony",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "bvncputxydfnuydmww5v",
      cuisines: ["Chinese", "North Indian", "Biryani"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 24,
      minDeliveryTime: 24,
      maxDeliveryTime: 24,
      slaString: "24 MINS",
      lastMileTravel: 1,
      slugs: { restaurant: "aibaik-ss-colony-ss-colony", city: "madurai" },
      cityState: "49",
      address: "Near Navavel Tower, By Pass Road, SS Colony, Madurai",
      locality: "Bypass Road",
      parentId: 7496,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "82025",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.9",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "80916",
      name: "Anjappar",
      uuid: "e5517414-106d-47a3-ada2-79ca9efc3f5d",
      city: "49",
      area: "Bethaniyapuram",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "bmrnu9i7zs8ftrnv8gtq",
      cuisines: ["South Indian", "Chinese", "Chettinad", "Desserts"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: "19 MINS",
      lastMileTravel: 1.100000023841858,
      slugs: {
        restaurant: "anjappar-restaurant-bethaniyapuram-ss-colony",
        city: "madurai",
      },
      cityState: "49",
      address:
        "215, A/3 RMJ Plaza, Madurai Theni Main Road, PP Chavadi, Bethaniyapuram, Madurai",
      locality: "Theni main road",
      parentId: 61,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "1.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "80916",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 1.100000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "81466",
      name: "Express Biriyani",
      uuid: "c395eb58-36ac-4aef-867b-a167027e611f",
      city: "49",
      area: "Sathamangalam",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "iwizeqkm4x6iiqctn7ho",
      cuisines: ["Biryani", "Chettinad", "Chinese", "South Indian"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      slaString: "29 MINS",
      lastMileTravel: 7.599999904632568,
      slugs: {
        restaurant: "express-briyani-sathamangalam-vandiyur",
        city: "madurai",
      },
      cityState: "49",
      address: "No: 135,2nd east main road, anna nagar,madurai",
      locality: "Anna Nagar",
      parentId: 8871,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 4400, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 4400,
        message: "",
        title: "Delivery Charge",
        amount: "4400",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6621705~p=10~eid=00000188-2583-b561-5439-576300710a4b",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "7.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "81466",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        lastMileTravel: 7.599999904632568,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.0",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "411122",
      name: "NammA AmmaN",
      uuid: "a9af6da7-b0f8-452f-9666-38296c8ffa87",
      city: "49",
      area: "Doak Nagar",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "hqoewhe6dacbjnwx8ugp",
      cuisines: ["North Indian", "South Indian", "Biryani"],
      tags: [],
      costForTwo: 10000,
      costForTwoString: "₹100 FOR TWO",
      deliveryTime: 18,
      minDeliveryTime: 18,
      maxDeliveryTime: 18,
      slaString: "18 MINS",
      lastMileTravel: 1.100000023841858,
      slugs: { restaurant: "namma-amman-periyar-periyar", city: "madurai" },
      cityState: "49",
      address: "Chavadi, Sammatipuram, Madurai, Tamil Nadu 625016, India",
      locality: "Kochadai Road",
      parentId: 143630,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "1.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "411122",
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        lastMileTravel: 1.100000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "666750",
      name: "Anifa Biriyani",
      uuid: "36019e57-aade-42a0-9e26-a24eae4dcc29",
      city: "49",
      area: "State Bank Colony Road",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "479370749fdfa9d528293916ee30ac7e",
      cuisines: [
        "Biryani",
        "South Indian",
        "North Indian",
        "Arabian",
        "Chinese",
        "Beverages",
        "Desserts",
      ],
      tags: [],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 22,
      minDeliveryTime: 22,
      maxDeliveryTime: 22,
      slaString: "22 MINS",
      lastMileTravel: 0.699999988079071,
      slugs: {
        restaurant: "mohammed-anifa-biriyani-periyar-periyar",
        city: "madurai",
      },
      cityState: "49",
      address:
        "D.No: 19, State Bank Colony, Bypass Road, Madurai, TamilNadu-625016",
      locality: "Bypass Road",
      parentId: 294903,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "0.6 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "666750",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        lastMileTravel: 0.699999988079071,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "491373",
      name: "Madurai Meenatchi Hotel",
      uuid: "46154019-ff8c-4fe7-a233-f8f435a8d501",
      city: "49",
      area: "Koodal Nagar",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "ezeq7clo4g01uaoqhnex",
      cuisines: ["Chinese", "North Indian", "South Indian", "Sweets"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 24,
      minDeliveryTime: 24,
      maxDeliveryTime: 24,
      slaString: "24 MINS",
      lastMileTravel: 3.700000047683716,
      slugs: {
        restaurant: "madurai-meenatchi-hotel-koodal-nagar-koodal-nagar",
        city: "madurai",
      },
      cityState: "49",
      address:
        "PALAMEDU MAIN ROAD, NEAR SBI BANK,  KOODAL NAGAR, WARD-1, MADURAI-625018",
      locality: "Prbha Complex",
      parentId: 294723,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6792733~p=13~eid=00000188-2583-b561-5439-576400710d3c",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "3.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "491373",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        lastMileTravel: 3.700000047683716,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.9",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "652511",
      name: "Bodhi Indo-Lankan Cuisine\t",
      uuid: "8428435d-e91d-457a-bd73-594814a056ef",
      city: "49",
      area: "SS Colony",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "bf458a8258369a40528c489f3463a77d",
      cuisines: ["South Indian", "Indian", "Snacks"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      slaString: "30 MINS",
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant: "bodhi-indo-lankan-cuisine-ss-colony-ss-colony",
        city: "madurai",
      },
      cityState: "49",
      address:
        "No.138A, S.S.Complex, Thirumalai  Colony Main Road, Kalavasal,  Madurai, Madurai Corporation  Ward-19, Madurai, Tamil Nadu,  625016",
      locality: "Thirumalai Colony",
      parentId: 392671,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "0.4 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "15% OFF",
        subHeader: "UPTO ₹45",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "652511",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.5",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "195456",
      name: "Medicine Unavagam",
      uuid: "48b0e1b0-7e20-4637-ab7a-264cee0dc748",
      city: "49",
      area: "Doak Nagar",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "jloxnrzyz2vrlghpdo3j",
      cuisines: ["Chinese", "North Indian", "South Indian"],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 20,
      minDeliveryTime: 20,
      maxDeliveryTime: 20,
      slaString: "20 MINS",
      lastMileTravel: 1,
      slugs: {
        restaurant: "medicine-unavagam-iyer-bungalow-iyer-bungalow",
        city: "madurai",
      },
      cityState: "49",
      address:
        "Oppo to J.K. Fenner (India) Limited, Doak Nagar, Madurai, Tamil Nadu, India",
      locality: "Melakkal road",
      parentId: 134638,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "1 kms",
      hasSurge: false,
      sla: {
        restaurantId: "195456",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "82937",
      name: "Charles Chicken",
      uuid: "68bd092f-cd9d-4479-aa72-d0042ef4ea81",
      city: "49",
      area: "Iyer Bungalow",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "tqzagvfny7sgivx5hpoj",
      cuisines: ["Chinese", "North Indian", "South Indian", "Biryani"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 27,
      minDeliveryTime: 27,
      maxDeliveryTime: 27,
      slaString: "27 MINS",
      lastMileTravel: 7.900000095367432,
      slugs: {
        restaurant: "chrales-chicken-iyer-banglow-iyer-bungalow",
        city: "madurai",
      },
      cityState: "49",
      address:
        "Natham Rd, Kurinjinagar, Cs Nagar, Sivakami Nagar, Tamil Nadu 625014",
      locality: "Natham Road",
      parentId: 6390,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 4400, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 4400,
        message: "",
        title: "Delivery Charge",
        amount: "4400",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6621743~p=16~eid=00000188-2583-b561-5439-576500711058",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "7.9 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "82937",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        lastMileTravel: 7.900000095367432,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.1",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
]
